### PR TITLE
Better wording in error msg

### PR DESCRIPTION
**Pull request by staabm**
The new message uses the same term, we use in the api: `exec`

### CODE REVIEW

**Comment by bwoebi** [comment]
Not sure, launching means starting, executing is starting&waiting for result. At least to my understanding…?

**Comment by staabm** [comment]
But you expect the user to call exec() before?

**Comment by kelunik** [comment]
Yes, but `exec` just starts the execution, it doesn't wait for it to complete.

**Comment by kelunik** [comment]
Tests segfault btw.: https://travis-ci.org/amphp/process/jobs/98862914

**Comment by staabm** [comment]
What do you think of: `Process was not yet launched, call exec() beforehand`

**Pull request closed without merging**
