### PR TITLE
define lower bound php-version

### PR DESCRIPTION
**Pull request by staabm**
as discussed for *nix systems 5.4 is enough for win 5.5+ is recommended

### CODE REVIEW

**Comment by bwoebi** [comment]
Is there any way how to specify a Windows specific requirement?

**Comment by staabm** [comment]
I am not aware of one

**Comment by kelunik** [comment]
I don't think so. Why is it 5.5 on Windows?

**Comment by bwoebi** [comment]
@staabm 5.4 is only needed because Amp needs it. If Amp were supporting 5.3, it would work there too on *nix.

I prefer to not add my own requirement here, but let the minimum version of this lib be implicitly defined by Amp.

@kelunik There exist bugs like https://bugs.php.net/bug.php?id=51800 which prevent this lib from working in every case… This failure is Windows specific though…

**Pull request closed without merging**
