### PR TITLE
Close all FDs in spawned process, because PHP leaks them

### PR DESCRIPTION
**Pull request by kelunik**
This might fix https://github.com/amphp/aerys/issues/192, @brstgt please test it.

@bwoebi Please test whether that works on macOS.

This should have a test, but I've not been able to write one yet.

It works locally, but apparently doesn't work on Travis, needs further investigation.

### CODE REVIEW

**Comment by bwoebi** [comment]
There's no procfs on macos, so no, that won't work. Also looks quite expensive to do...

**Comment by kelunik** [comment]
I don't care how expensive that is as long as it fixes the bug for now. Do you see another possibility?

**Comment by brstgt** [comment]
https://stackoverflow.com/questions/20974438/get-list-of-open-files-descriptors-in-os-x

See last comment

2017-10-09 14:16 GMT+02:00 Niklas Keller <notifications@github.com>:

**Comment by kelunik** [comment]
The issue is that Travis runs `dash`, which doesn't support redirection FDs higher than 9.

**Comment by kelunik** [comment]
I'm closing this PR as it's not cross-platform.

**Pull request closed without merging**
